NapocaBike/Pages/BikeParkingsList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NapocaBike.Pages
{
    public class BikeParkingsListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NapocaBike/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace NapocaBike.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NapocaBike/Pages/GoogleMapsApiProxy.cshtml.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace NapocaBike.Pages
{
    public class GoogleMapsApiProxyModel : PageModel
    {
        private readonly IConfiguration _configuration;

        public GoogleMapsApiProxyModel(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            string googleMapsApiBaseUrl = "https://maps.googleapis.com/maps/api/js";
            string apiKey = _configuration["GoogleMaps:ApiKey"];

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync($"{googleMapsApiBaseUrl}?key={apiKey}&libraries=geometry&libraries=geocoding&callback=initMap&v=weekly");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    return Content(content, "application/javascript");
                }
            }

            return NotFound();
        }
    }
}

NapocaBike/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NapocaBike.Data;
using NapocaBike.Models;

namespace NapocaBike.Pages
{
    public class IndexModel : BasePageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, UserManager<IdentityUser> userManager, NapocaBikeContext context, RoleManager<IdentityRole> roleManager)
            : base(userManager, context, roleManager)
        {
            _logger = logger;
        }

        public Member CurrentMember { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                CurrentMember = await _context.Member.FirstOrDefaultAsync(m => m.Email == user.Email);
            }
            await LoadUserDataAsync();
            return Page();
        }
    }
}

NapocaBike/Pages/LocationsList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NapocaBike.Pages
{
    public class LocationsListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NapocaBike/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NapocaBike.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

NapocaBike/Pages/Propose.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NapocaBike.Data;
using NapocaBike.Models;

namespace NapocaBike.Pages.BikeParkings.Propose
{
    [Authorize]
    public class ProposeModel : PageModel
    {
        private readonly NapocaBike.Data.NapocaBikeContext _context;

        public ProposeModel(NapocaBike.Data.NapocaBikeContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ProposedBikeParking ProposedBikeParking { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ProposedBikeParking.IsApproved = false;
            _context.ProposedBikeParkings.Add(ProposedBikeParking);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

NapocaBike/Pages/ProposeLocation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NapocaBike.Pages
{
    public class ProposeLocationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NapocaBike/Pages/RentalsList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NapocaBike.Pages
{
    public class RentalsListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NapocaBike/Pages/ReviewProposals.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NapocaBike.Data;
using NapocaBike.Models;

namespace NapocaBike.Pages.BikeParkings.ReviewProposals
{
    //[Authorize(Roles = "Admin")]
    public class ReviewProposalsModel : PageModel
    {
        private readonly NapocaBike.Data.NapocaBikeContext _context;

        public ReviewProposalsModel(NapocaBike.Data.NapocaBikeContext context)
        {
            _context = context;
        }

        public IList<ProposedBikeParking> ProposedBikeParkings { get; set; }
        public IList<Location> Location { get; set; }

        public async Task OnGetAsync()
        {
            ProposedBikeParkings = await _context.ProposedBikeParkings
                .Where(p => !p.IsApproved)
                .ToListAsync();

            Location = await _context.Location
                .Where(l => !l.IsApproved)
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostApproveAsync(int id)
        {
            var proposedBikeParking = await _context.ProposedBikeParkings.FindAsync(id);

            if (proposedBikeParking != null)
            {
                _context.BikeParking.Add(new BikeParking
                {
                
                    Name = proposedBikeParking.Name,
                    Latitude = proposedBikeParking.Latitude,
                    Longitude = proposedBikeParking.Longitude,
                    Capacity = proposedBikeParking.Capacity,
                    SecurityLevel = proposedBikeParking.SecurityLevel
                });

                _context.ProposedBikeParkings.Remove(proposedBikeParking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }


        public async Task<IActionResult> OnPostRejectAsync(int id)
        {
            var proposedBikeParking = await _context.ProposedBikeParkings.FindAsync(id);

            if (proposedBikeParking != null)
            {
                _context.ProposedBikeParkings.Remove(proposedBikeParking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }



        public async Task<IActionResult> OnPostApproveLocationAsync(int id)
        {
            var proposedLocation = await _context.Location.FindAsync(id);

            if (proposedLocation != null)
            {
                proposedLocation.IsApproved = true;
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRejectLocationAsync(int id)
        {
            Location location = await _context.Location.FindAsync(id);

            if (location != null)
            {
                _context.Location.Remove(location);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

    }
}

NapocaBike/Pages/UpdateProfile.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NapocaBike.Data;
using NapocaBike.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace NapocaBike.Pages
{
    public class UpdateProfileModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly NapocaBikeContext _context;

        public UpdateProfileModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, NapocaBikeContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [BindProperty]
        public Member Member { get; set; }
        
        [BindProperty]
        [Display(Name = "Profile Picture")]
        public IFormFile ProfilePicture { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Index");
            }

            Member = await _context.Member.FirstOrDefaultAsync(m => m.Email == user.Email);

            if (Member == null)
            {
                // Handle the case when the Member is not found in the database
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Index");
            }

            var existingMember = await _context.Member.FirstOrDefaultAsync(m => m.Email == user.Email);
            if (existingMember == null)
            {
                return Page();
            }

            existingMember.FirstName = Member.FirstName;
            existingMember.LastName = Member.LastName;
            existingMember.Adress = Member.Adress;
            existingMember.Phone = Member.Phone;

            if (ProfilePicture != null && ProfilePicture.Length > 0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(ProfilePicture.FileName);  
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ProfilePicture.CopyToAsync(fileStream);
                }
                existingMember.ProfilePicturePath = "/images/" + fileName;
            }

            // Save the changes
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                // Handle exceptions while updating the database
            }

            return RedirectToPage("/Index");
        }


    }
}

NapocaBike/Pages/GoogleMapsApiProxy.cshtml
@page
@model NapocaBike.Pages.GoogleMapsApiProxyModel
@{
}

NapocaBike/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Welcome Page";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bike Napoca</title>
    <link rel="stylesheet" href="~/css/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
   <style>

        .dropdown {
            position: relative;
        }

        .dropdown-toggle {
            cursor: pointer;
        }

        .dropdown-menu {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-menu .dropdown-item {
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-menu .dropdown-item:hover {
                    background-color: #D9AF32;
                }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .login-container {
            display: flex;
            align-items: center;
            margin-left: auto;
            padding-left: 30px;
        }

        /* Login Modal */
        .login-btn {
            cursor: pointer;
        }

        .login-modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.4);
        }

        .modal-content {
            background-color: #ffffff;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 50%; 
            max-width: 400px; 
        }
        
   </style>
</head>

<body>
  
    <section>
        <input type="checkbox" id="check">
        <header>
            <h2><a href="#" class="logo"> Napoca Bike </a></h2>


            <div class="navigation">
                <a asp-area="" asp-page="/LocationsList" class="menu-item">Locations</a>
                <a asp-area="" asp-page="/BikeParkingsList" class="menu-item">Parkings</a>
                <a asp-area="" asp-page="/RentalsList" class="menu-item">Rentals</a>
                

                <div class="menu-item dropdown">
                    <a href="#" class="dropdown-toggle">Propose</a>
                    <div class="dropdown-menu">
                        <a asp-area="" asp-page="/Propose" class="menu-item">Parking</a>
                        <a asp-area="" asp-page="/ProposeLocation" class="menu-item">Location</a>

                    </div>
                </div>
                @if (Model.IsAdmin)
                {
                    <div class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle">Admin</a>
                        <div class="dropdown-menu">
                            <a asp-area="" asp-page="/BikeRentalLocations/Index" class="dropdown-item ">AdminRentals</a>
                            <a asp-area="" asp-page="/BikeParkings/Index" class="dropdown-item">AdminParkings</a>
                            <a asp-area="" asp-page="/Locations/Index" class="dropdown-item">AdminLocations</a>
                            <a asp-area="" asp-page="/Categories/Index" class="dropdown-item">Categories</a>
                            <a asp-area="" asp-page="/Members/Index" class="dropdown-item">Members</a>

                            <a asp-area="" asp-page="/ReviewProposals" class="menu-item">ReviewProposals</a>
                        </div>
                    </div>
                }

                
                <div class="menu-item">
                    @if (Model.CurrentMember != null && !string.IsNullOrEmpty(Model.CurrentMember.ProfilePicturePath))
                    {
                        <img id="login-btn" class="login-btn"  src="@Model.CurrentMember.ProfilePicturePath" alt="Profile Picture" width="40" height="40" style="border-radius: 50%;" />
                    }
                    else
                    {
                        <a id="login-btn" class="login-btn">Login</a>
                    }
                </div>


                
            </div>
           
            <label for="check">
                <i class="fas fa-bars menu-btn"></i>
                <i class="fas fa-times close-btn"></i>
            </label>


        </header>

        <div id="login-modal" class="login-modal">
            <div class="modal-content">
               
                    <partial name="_LoginPartial" />
                
            </div>
        </div>


        <div class="content">
            <div class="info">
                <h2>Start pedaling<br><span>Be free!</span></h2>
                <a asp-area="" asp-page="/LocationsList" class="info-btn">View locations</a>
            </div>
        </div>
        <div class="media-icons">
            <a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
        </div>
    </section>

    <script>
        
        var modal = document.getElementById("login-modal");

       
        var btn = document.getElementById("login-btn");

    
        btn.onclick = function () {
            modal.style.display = "block";
        };

        
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        };
    </script>

</body>
</html>

NapocaBike/Pages/Propose.cshtml
@page
@model NapocaBike.Pages.BikeParkings.Propose.ProposeModel
@{
    ViewData["Title"] = "Propose";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Propose a Bike Parking</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <style>
      
        .row {
            display: flex;
            flex-wrap: wrap;
            margin-left: -15px;
            margin-right: -15px;
        }

        .col-md-4,
        .col-md-8 {
            position: relative;
            width: 100%;
            padding-left: 15px;
            padding-right: 15px;
        }

        .col-md-4 {
            flex: 0 0 33.333333%;
            max-width: 33.333333%;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
        }

        .col-md-8 {
            flex: 0 0 66.666667%;
            max-width: 66.666667%;
            padding-left: 30px;
        }

        h1 {
            font-family: 'Poppins', sans-serif;
            font-weight: 600;
            color: #226A80;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 1rem;
        }

        .form-control {
            display: block;
            width: 100%;
            padding: .375rem .75rem;
            font-size: 1rem;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
            margin-bottom: 5px;
        }

        .btn-primary {
            color: #fff;
            background-color: #D9AF32;
            border-color: #D9AF32;
            font-family: 'Poppins', sans-serif;
        }

            .btn-primary:hover {
                background-color: #F25050;
                border-color: #F25050;
            }

        #map {
            background-color: #f8f9fa;
            border-radius: 10px;
            box-shadow: 0 1px 3px rgba(0,0,0,.05), 0 1px 2px rgba(0,0,0,.1);
        }

        a {
            color: #D9AF32;
            text-decoration: none;
            font-family: 'Poppins', sans-serif;
            font-weight: 600;
        }

            a:hover {
                color: #F25050;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <h1>Propose a Bike Parking</h1>


    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ProposedBikeParking.Name" class="control-label"></label>
                    <input asp-for="ProposedBikeParking.Name" class="form-control" />
                    <span asp-validation-for="ProposedBikeParking.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProposedBikeParking.Latitude" class="control-label"></label>
                    <input asp-for="ProposedBikeParking.Latitude" id="Latitude" class="form-control" />
                    <span asp-validation-for="ProposedBikeParking.Latitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProposedBikeParking.Longitude" class="control-label"></label>
                    <input asp-for="ProposedBikeParking.Longitude" id="Longitude" class="form-control" />
                    <span asp-validation-for="ProposedBikeParking.Longitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProposedBikeParking.Capacity" class="control-label"></label>
                    <input asp-for="ProposedBikeParking.Capacity" class="form-control" />
                    <span asp-validation-for="ProposedBikeParking.Capacity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProposedBikeParking.SecurityLevel" class="control-label"></label>
                    <input asp-for="ProposedBikeParking.SecurityLevel" class="form-control" />
                    <span asp-validation-for="ProposedBikeParking.SecurityLevel" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Propose" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <div class="col-md-8">
            <div id="map" style="height: 400px;"></div>
        </div>
    </div>

    <div>
        <a asp-page="./Index">Back to Main page</a>
    </div>
</body>
</html>


@section Scripts {
    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById("map"), {
                center: { lat: 46.770439, lng: 23.591423 },
                zoom: 10,
                mapId: 'fd46ebf30d389dd2',
            });
            var marker = new google.maps.Marker({
                position: { lat: 46.770439, lng: 23.591423 },
                map: map,
                draggable: true,
            });
            marker.addListener("dragend", function () {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                document.getElementById("Latitude").value = lat;
                document.getElementById("Longitude").value = lng;
            });
        }
    </script>
    <script src="~/GoogleMapsApiProxy" async defer></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NapocaBike/Pages/ReviewProposals.cshtml
@page
@model NapocaBike.Pages.BikeParkings.ReviewProposals.ReviewProposalsModel
@{
    ViewData["Title"] = "Review Proposals";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/review.css">
</head>
<body>
    <h2>Review Bike Parking Proposals</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Capacity</th>
                <th>Security Level</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var proposedBikeParking in Model.ProposedBikeParkings)
            {
                <tr>
                    <td>@proposedBikeParking.Name</td>
                    <td>@proposedBikeParking.Latitude</td>
                    <td>@proposedBikeParking.Longitude</td>
                    <td>@proposedBikeParking.Capacity</td>
                    <td>@proposedBikeParking.SecurityLevel</td>
                    <td>
                        <form method="post">
                            <input type="hidden" asp-for="@proposedBikeParking.ID" name="id" />
                            <button type="submit" asp-page-handler="Approve" class="btn btn-primary">Approve</button>
                            <button type="submit" asp-page-handler="Reject" class="btn btn-danger ml-2">Reject</button>

                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <h2>Review Location Proposals</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Adress</th>
                <th>Program</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Website</th>
                <th>CUI</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Categories</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var proposedLocation in Model.Location)
            {
                <tr>
                    <td>@proposedLocation.Name</td>
                    <td>@proposedLocation.Adress</td>
                    <td>@proposedLocation.Program</td>
                    <td>@proposedLocation.Phone</td>
                    <td>@proposedLocation.Email</td>
                    <td>@proposedLocation.Website</td>
                    <td>@proposedLocation.CompanyRegistrationNumber</td>

                    <td>@proposedLocation.Latitude</td>
                    <td>@proposedLocation.Longitude</td>
                    <td>@proposedLocation.LocationCategories.</td>
                    <td>
                        <form method="post">
                            <input type="hidden" asp-for="@proposedLocation.ID" name="id" />
                            <button type="submit" asp-page-handler="ApproveLocation" class="btn btn-primary">Approve</button>
                            <button type="submit" asp-page-handler="RejectLocation" class="btn btn-danger ml-2">Reject</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        <a asp-page="./Index">Back to List</a>
    </div>

</body>